### ISSUE TITLE
Compatibility with Capacitor 2.0.2

### ISSUE THREAD

**Issue by pufanalexandru** [cleversolutions/zebraCapacitor#2]
Hello,

Is this plugin compatible with Capacitor 2.0.2?
I installed it using `npm install --save zebra-capacitor`, but there's no way I can import it into my files (with something like `import { zebra-capacitpr } from 'zebra-capacitor'`.  Are there any other configurations needed, or is the plugin not compatible with my version of Capacitor?

**Comment by dieasmaz** [comment]
Hi @pufanalexandru!

**ATENTION!** I'm currently using capacitor 1.5.0 but you can try, maybe works.

I was testing this a moment ago, let me show you what i was doing.

1. `npm i zebra-capacitor --save`
2. Open the file `MainActivity.java` (or your AppActivity.java) and do this:
        a. Add import `import ca.cleversolutions.zebracapacitor.ZebraPrinter;`
        b. Register Class `
    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      add(ZebraPrinter.class);
    }});`
3. In your file (.ts for me) import like this:
   ` import { Plugins } from '@capacitor/core';
import {
  ZebraPlugin,
  DiscoveryResult,
  Printer,
} from 'zebra-capacitor/dist/esm/index';
const zebraPlugin = Plugins.ZebraPrinter as ZebraPlugin;
`
4. Then use the plugin in your method
`discoveredPrinters = await zebraPlugin.discover();`

Hope this helps!

**Comment by cleversolutions** [comment]
Hi @pufanalexandru, sorry this is a really late reply. I've used this with Capacitor version 2.4.5. I'm not 100% sure if it works with 2.0.2, but similar to @dieasmaz said in my .ts file I use the plugin like below:
```
import { Plugins } from '@capacitor/core';
import 'zebra-capacitor'; 
import { ZebraPrinter, ZebraDiscoveryResult, ZebraPrinterStatus } from 'zebra-capacitor';
const { ZebraCapacitorPlugin } = Plugins;

...

public connect(printer: Printer): Observable<boolean> {
    return new Observable(observer => {
      ZebraCapacitorPlugin
        .connect({ MACAddress: printer.address })
        .then(async () => {
          this.currentPrinter = printer;
          observer.next(true);
          observer.complete();
        })
        .catch(err => {
          observer.error(err);
          observer.complete();
        });
    });
  }
```
